[aws]
disabled = true
symbol = "  "

[azure]
disabled = true

[buf]
disabled = true
symbol = " "

[bun]
disabled = true

[c]
disabled = true
symbol = " "

[cmake]
disabled = true

[cobol]
disabled = true

[conda]
disabled = true
symbol = " "

[crystal]
disabled = true
symbol = " "

[daml]
disabled = true

[dart]
disabled = true
symbol = " "

[deno]
disabled = true

[directory]
read_only = " 󰌾"

[docker_context]
symbol = " "

[dotnet]
disabled = true

[elixir]
disabled = true
symbol = " "

[elm]
disabled = true
symbol = " "

[erlang]
disabled = true

[fennel]
disabled = true
symbol = " "

[fossil_branch]
symbol = " "

[gcloud]
disabled = true

[git_branch]
symbol = " "

[golang]
symbol = " "

[guix_shell]
disabled = true
symbol = " "

[haskell]
symbol = " "

[haxe]
disabled = true
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[julia]
disabled = true
symbol = " "

[kotlin]
symbol = " "

[lua]
disabled = true
symbol = " "

[localip]
ssh_only = true
disabled = false

[memory_usage]
symbol = "󰍛 "

[meson]
disabled = true
symbol = "󰔷 "

[nats]
disabled = true

[nim]
disabled = true
symbol = "󰆥 "

[nix_shell]
disabled = true
symbol = " "

[nodejs]
symbol = " "

[ocaml]
disabled = true
symbol = " "

[opa]
disabled = true

[openstack]
disabled = true

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
disabled = true
symbol = "󰏗 "

[perl]
disabled = true
symbol = " "

[php]
disabled = true
symbol = " "

[pijul_channel]
disabled = true
symbol = " "

[purescript]
disabled = true

[python]
symbol = " "

[quarto]
disabled = true

[rlang]
disabled = true
symbol = "󰟔 "

[raku]
disabled = true

[red]
disabled = true

[ruby]
disabled = true
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
disabled = true
symbol = " "

[singularity]
disabled = true

[solidity]
disabled = true

[spack]
disabled = true

[swift]
disabled = true
symbol = " "

[typst]
disabled = true

[vagrant]
disabled = true

[vlang]
disabled = true

[vcsh]
disabled = true

[zig]
disabled = true
symbol = " "
